### ISSUE TITLE
Bower dependencies are never pinned

### ISSUE THREAD

**Issue by markfinger** [ixc/ixc-project-template#33]
Default bower deps are currently set to

```js
{
  // ..
  "dependencies": {
    "jquery": null,
    "bootstrap": null,
    "lodash": null,
    "font-awesome": null
  }
}
```

This makes project initialisation easy, but it introduces a maintenance overhead as most projects have never pinned those versions.

Easiest work around is to run the following during project creation:

```
bower install --save jquery bootstrap lodash font-awesome
```

This installs the deps and will pin their versions automatically.

**Comment by markfinger** [comment]
@mrmachine assuming my suggestion is tolerable, where would be the best place to make changes to the init script?

**Comment by mrmachine** [comment]
@markfinger this is probably redundant now (or soon) -- https://github.com/ic-labs/django-icekit/blob/feature/project/icekit/bower.json ... or if we did still want to update `ixc-project-template`, it might be best to just include a reminder note in the stdout from `startproject.sh` that this should be done. Bower might not be installed when the `startproject.sh` script runs, so we probably can't automate it. And can we do it with just `bower install -S` or something, without having to explicitly mention all the packages that are included in the `bower.json` file?

**Comment by markfinger** [comment]
I don't think there's a way to pin the dependencies automatically without specifying them as params to `bower`.

As you indicated, this'll probably be redundant if bower is being included in icekit.

**Comment by markfinger** [comment]
Actually, I'll leave this open until it's been solved one way or another.

**Comment by mrmachine** [comment]
@markfinger let's just pin them in `ixc-project-template`, instead of leaving them open and trying to remind people to pin them when they create a project.

**Comment by markfinger** [comment]
I've pinned them to current latest
