### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by markfinger** [ixc/ixc-project-template#6]
The docs state to add the remote as `git remote add origin git@github.com/ixc/<project>.git` 

but git threw up the following 
```
fatal: 'git@github.com/ixc/<project>.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I actually had to specify it as `git remote add origin git@github.com:ixc/<project>.git`. The only difference seems to be the colon, presumably suggesting SSH over HTTPS.

```
$ git --version
git version 2.2.1
```

**Comment by mrmachine** [comment]
Good catch. Thanks!
