### ISSUE TITLE
Default DEBUG setting

### ISSUE THREAD

**Issue by markfinger** [ixc/ixc-project-template#7]
On a couple of projects I've experienced issues with setting up the dev env only to realise - after trying to resolve the issues - that it was caused by the DEBUG setting being False.

Given that the majority of our use cases are developers setting up a project, would it be wiser to have DEBUG set to True? As in, to treat production instances as the edge case, rather than the norm.

**Comment by sjdines** [comment]
I don't think this would be wiser but could lead to more serious problems on a production server. I think the developer should configure their local.py with thought for their use case and machine e.g. setting the database config. Having commented out local templates and developers ACTUALLY reading them I believe is key. This can be done by keeping local to relevant items.

**Comment by markfinger** [comment]
Closing as Stu is right, as always

**Comment by sjdines** [comment]
Haha @markfinger sorry; I know you dislike reading
